<h2> This is your blog </h2>
<table>
    <?php foreach ($this->posts as $p):?>
    <tr>
        <td>
            <a href="<?php echo $this->url(array('id' => ($p['PostID'])), 'shm-post'); ?>">
                <h3><?php echo $this->escape($p['PostName']); ?></h3>
            </a>
        </td>
    </tr>
    <tr>
        <td>
            <?php echo $this->escape($p['PostBody']); ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>