<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <base href="/" />
        <!-- <link rel="stylesheet" type="text/css" href="/css/main.css" /> -->
    </head>
    <style>
        #menu a{
            border: 2px blue solid;
            padding: 4px;
        }

        #content{
            border: 1px green solid;
            margin-top: 10px;
            padding: 4px;
        }

        table {
            border: solid 1px black;
            border-collapse: collapse;
            border-spacing: 0px;
        }

        td {
            border: solid 1px black;
            padding: 5px;
        }

        td.key {
            font-weight: bold;
            vertical-align: top;
        }
    </style>

    <body>
        <div id="header">
            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                <h2>Your login is "<?php echo Zend_Auth::getInstance()->getIdentity(); ?>".</h2>
            <?php endif; ?>
            <div id="menu">
                <a href="<?php echo $this->url(array(), 'home'); ?>">HOME</a>
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                    <a href="<?php echo $this->url(array(), 'account'); ?>">MY ACCOUNT</a>
                    <a href="<?php echo $this->url(array(), 'logout'); ?>">LOGOUT</a>
                <?php else: ?>
                    <a href="<?php echo $this->url(array(), 'login'); ?>">LOGIN</a>
                    <a href="<?php echo $this->url(array(), 'register'); ?>">REGISTER</a>
                <?php endif; ?>

            </div>
        </div>
        <div id="content">
            <?php echo $this->layout()->content ?>
        </div>
    </body>
</html>

