<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <base href="/" />
        <link rel="stylesheet" type="text/css" href="/css/main.css" />
    </head>
    <body>
        <div id="header">
            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                <h2>Your login is "<?php echo Zend_Auth::getInstance()->getIdentity(); ?>".</h2>
            <?php endif; ?>
            <div id="menu">
                <a href="<?php echo $this->url(array(), 'home'); ?>">HOME</a>
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                    <a href="<?php echo $this->url(array(), 'logout'); ?>">LOGOUT</a>
                    <a href="<?php echo $this->url(array(), 'account'); ?>">MY ACCOUNT</a>
                    <a href="<?php echo $this->url(array(), 'blog'); ?>">MY BLOG</a>
                <?php else: ?>
                    <a href="<?php echo $this->url(array(), 'login'); ?>">LOGIN</a>
                    <a href="<?php echo $this->url(array(), 'register'); ?>">REGISTER</a>
                <?php endif; ?>
            </div>
            <div id="menu2">
                <a href="<?php echo $this->url(array(), 'c-blog'); ?>">Создать блог</a>
            </div>
        </div>
        <div id="content">
            <?php echo $this->layout()->content ?>
        </div>
    </body>
</html>

